name: finance-agent
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - fastapi=0.110.0
  - pandas=2.2.2
  - pydantic=2.6.3
  - numpy=1.26.4
  - requests=2.31.0
  - uvicorn=0.28.0
  - yfinance=0.2.52
  - pip:
      - finance-datareader==0.9.96
