from __future__ import annotations

import json
from datetime import datetime, UTC
from pathlib import Path

from ..models import LeanProjectArtifact, StrategyRequest
from ..strategies.base import StrategySpec


class LeanProjectBuilder:
    def __init__(self, base_dir: Path) -> None:
        self.base_dir = base_dir

    def build(self, run_id: str, strategy: StrategySpec, request: StrategyRequest) -> LeanProjectArtifact:
        project_name = f"{strategy.key}-{request.ticker.lower()}-{run_id[:8]}"
        project_dir = self.base_dir / project_name
        project_dir.mkdir(parents=True, exist_ok=False)

        main_file = project_dir / "main.py"
        config_file = project_dir / "config.json"
        kis_live_file = project_dir / "kis_live.json"
        manifest_file = project_dir / "framework_manifest.json"
        readme_file = project_dir / "README.md"

        main_file.write_text(strategy.render_lean_algorithm(request), encoding="utf-8")
        config_file.write_text(
            json.dumps(strategy.render_project_config(request), indent=2),
            encoding="utf-8",
        )
        kis_live_file.write_text(
            json.dumps(strategy.render_live_manifest(request), indent=2),
            encoding="utf-8",
        )
        manifest_file.write_text(
            json.dumps(
                {
                    "run_id": run_id,
                    "generated_at": datetime.now(UTC).isoformat(),
                    "strategy_key": strategy.key,
                    "request": request.model_dump(mode="json"),
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        readme_file.write_text(
            self._render_readme(project_name=project_name, strategy=strategy, request=request),
            encoding="utf-8",
        )

        suggested_command = f'cd "{project_dir.parent}" && lean backtest "{project_name}"'

        return LeanProjectArtifact(
            project_name=project_name,
            project_dir=project_dir,
            main_file=main_file,
            config_file=config_file,
            kis_live_file=kis_live_file,
            manifest_file=manifest_file,
            readme_file=readme_file,
            suggested_command=suggested_command,
        )

    def _render_readme(
        self,
        project_name: str,
        strategy: StrategySpec,
        request: StrategyRequest,
    ) -> str:
        return f"""# {project_name}

This Lean project was generated by the local Lean + KIS framework.

## Strategy

- Strategy key: `{strategy.key}`
- Strategy name: `{strategy.name}`
- Ticker: `{request.ticker}`
- Market tag: `{request.market}`
- Resolution: `{request.resolution}`

## Files

- `main.py`: Lean algorithm entrypoint
- `config.json`: Lean project parameters
- `kis_live.json`: live execution hand-off manifest for the KIS adapter
- `framework_manifest.json`: generated metadata for this run

## How to use

1. Install and initialize the Lean CLI in your workspace.
2. Ensure your local Lean data source is available for the target ticker and market.
3. Run:

```bash
cd "{self.base_dir}"
lean backtest "{project_name}"
```

## Live trading note

This scaffold intentionally separates the backtest leg from the brokerage leg.
Lean owns research and backtests. The KIS adapter owns order routing and account credentials.
"""
